name: travel develop server CI/CD

on:
  push:
    branches: [ server_develop_test]
  pull_request:
    branches: [ server_develop_test]

env:
  S3_BUCKET_NAME: travel-deploy

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
